### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#11]
An extra `w` .
Even without the `w`, the file [does not exist](http://www.ducs.in/sankalan/terms). It's time to make one.

![screenshot 148](https://user-images.githubusercontent.com/13359891/36227273-947b0904-11f6-11e8-8a4a-30d967c22ea6.png)

**Comment by sidvishnoi** [comment]
This is DNS issue. For a webserver that doesn't exist at this domain.
Not in our control.

**Comment by jatin69** [comment]
What ? lol
See the URL, its `wwww`
With the power of that `w`, even this fails `https://wwww.ducs.in/sankalan`

**Comment by sidvishnoi** [comment]
This didn't result in a 404 not found error. that error is in our control and is quick to fetch.
It is a DNS look up error. We cannot control things outside the scope of our website.

Also, with https, it will later result in "untrusted connection" warning from browser.

**Comment by jatin69** [comment]
👍 still an issue though. lol.
