### ISSUE TITLE
Footer needs work

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#12]
DUCSS looks right, but doesn't sound right. 

![screenshot 154](https://user-images.githubusercontent.com/13359891/36227383-f3ff20b8-11f6-11e8-984e-de99c71238fe.png)

**Comment by sidvishnoi** [comment]
Suggest alternative text

**Comment by jatin69** [comment]
Add a help wanted label. They maybe someone would.
