### ISSUE TITLE
Reduce redirects in registration workflow

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#13]
The register link from the homepage takes us to this page.
This page takes to google sign in icon page. 
Then i can go and click, and go to google, and back, and chill
A little too much. Maybe give the register button on this page itself.

![screenshot 151](https://user-images.githubusercontent.com/13359891/36227443-1a7fbf36-11f7-11e8-85c3-b9635b1d0488.png)

**Comment by sidvishnoi** [comment]
What do you suggest? Which click of following should start the google login process?
1. Register button on home page
2. Register button on register page
3. Register button on dashboard page (current)

**Comment by jatin69** [comment]
Number 2 should start the login process.
Once that's done, take me to dashboard page.
