### ISSUE TITLE
css needs fix on login page

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#19]
On page https://dashboard.ducs.in/sankalan/login
The half half distribution looks nice, a lil. But i guess it needs fix.
Bootstrap ref - put the form in 8 units (2 label + 6 text) instead of 12 units ( 6 label + 6 text ).
![sankalan_login](https://user-images.githubusercontent.com/13359891/36374515-90366ff2-1591-11e8-9e0f-dea9d2a77f4a.PNG)

**Comment by sidvishnoi** [comment]
Doesn't belong to this repository.

**Comment by jatin69** [comment]
should i post this on the another repo ?

**Comment by sidvishnoi** [comment]
yes. github.com/sidvishnoi/dashboard.ducs.in
