### ISSUE TITLE
Build Fails in case of missing assetsManifest file

### ISSUE THREAD

**Issue by rumansaleem** [sidvishnoi/sankalan-2018#36]
## Steps to reproduce
Follow the Readme instructions

## Current Behaviour
Following error shows up on `npm run build:dev`
```bash
[10:07:18] 'content' errored after 101 ms
[10:07:18] Error: Cannot find module '/hdd/code/sankalan-2018/src/template/assets.json'
```

## Expected Behaviour
Assets compile successfully and watcher should keep watching files for changes

## Reason
This is because of ignored file `src/template/assets.json`

## Possible Solution
`Readme.md` should have instructions to create an empty manifest file before running the `build:dev` script. Like so:

```bash
echo {} >> src/template/assets/json
```

or another way to handle this could be to check in gulp script, that if the file doesn't exist, create an empty json file (file containing `{}`).

However, the latter seems more intuitive.

**Comment by sidvishnoi** [comment]
Yes I was aware of this, but got lazy to not write that (and instead created that file manually  🙈)
Feel free to fix such bugs in the next build system, but I'm closing this issue as this repo is not to be maintained anymore.
