### ISSUE TITLE
Website still accessible on http

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#6]
Shouldn't every request be redirected to https by default ?

![http access](https://user-images.githubusercontent.com/13359891/36226729-b08b1ece-11f4-11e8-8a50-15d9082f9eee.png)

**Comment by sidvishnoi** [comment]
Not done intentionally. The website where SSL is required (dashboard.ducs.in) is always https.
There is no issue on this website if this stays available on http also.
Get upvotes, I'll make main website also https only :grin:

**Comment by jatin69** [comment]
lol. https looks good. feels good. 
If i am typing the site address by hand, i would never actually go to https.
Although we did go through the pain of https, half of the people will see how insecure they are.
Hoping for upvotes though.

**Comment by sidvishnoi** [comment]
You got the upvote. Website is now automatically redirected to https.
