### ISSUE TITLE
Need a loader animation until page loads

### ISSUE THREAD

**Issue by jatin69** [sidvishnoi/sankalan-2018#7]
Maybe adding a loader animation will make this right 

![screenshot 142](https://user-images.githubusercontent.com/13359891/36227001-9e987b16-11f5-11e8-8450-58d30754d02f.png)
![screenshot 144](https://user-images.githubusercontent.com/13359891/36227005-a167b8ac-11f5-11e8-9d72-842e1f1f688c.png)

**Comment by sidvishnoi** [comment]
Against philosophy (full page loader) - showing an indefinite loader animation gives user an impression of site not loading or being heavy. A user on slow internet might leave really soon seeing a full page loader.
Keeping things simple makes sure that user is able to see the progress of site loading.

**Comment by jatin69** [comment]
But the site is in fact light and takes 2 seconds to load. No one would mind a loader for 2 seconds.
Plus, this decreases the eye candy. I have been through loaders that take 5 seconds to load, 
A two second progressive loader, filling in quick will do good here.

**Comment by sidvishnoi** [comment]
Creating a progressive loader for a fixed time is not a good idea. If it takes more time to load, we still see an incomplete page. That could lead us to add an indefinite loader.
If the page is loaded early, that is not an issue. we can always hide the loader early.

:+1: for eye candy part.
Will add a small loader above and show the unloaded content below using some critical CSS embedded in HTML.

**Comment by jatin69** [comment]
I meant progressive, but obviously the one which shows true percentage. 
But yeah, too much work maybe.
👍  for the small loader, and if it could match the site theme, it would be 😎
